<?php

return [
    'capabilities' => [
        [
            'key' => 'dashboard.access',
            'label' => 'Acceso al dashboard',
            'description' => 'Permite ingresar al panel principal.',
            'order' => 10,
            'permissions' => [
                ['name' => 'dashboard.view', 'required' => true],
            ],
        ],
        [
            'key' => 'appointments.manage',
            'label' => 'Gestión de agenda',
            'description' => 'Gestiona citas, disponibilidad y cambios operativos con lectura requerida de técnicos.',
            'order' => 20,
            'permissions' => [
                ['name' => 'appointments.view', 'required' => true],
                ['name' => 'appointments.availability', 'required' => true],
                ['name' => 'technicians.view', 'required' => true],
                ['name' => 'appointments.create', 'required' => false],
                ['name' => 'appointments.reschedule', 'required' => false],
                ['name' => 'appointments.reassign_technician', 'required' => false],
                ['name' => 'appointments.cancel', 'required' => false],
                ['name' => 'appointments.confirm', 'required' => false],
                ['name' => 'customers.view', 'required' => true],
            ],
        ],
        [
            'key' => 'schedule.manage',
            'label' => 'Gestión de horarios',
            'description' => 'Administra jornada base, sobreescrituras y consulta de disponibilidad.',
            'order' => 30,
            'permissions' => [
                ['name' => 'schedule.view', 'required' => true],
                ['name' => 'schedule.availability', 'required' => true],
                ['name' => 'schedule.update', 'required' => false],
                ['name' => 'schedule.manage_overrides', 'required' => false],
            ],
        ],
        [
            'key' => 'customers.manage',
            'label' => 'Gestión de clientes',
            'description' => 'Administra CRUD, importaciones y exportaciones de clientes.',
            'order' => 40,
            'permissions' => [
                ['name' => 'customers.view', 'required' => true],
                ['name' => 'customers.create', 'required' => false],
                ['name' => 'customers.update', 'required' => false],
                ['name' => 'customers.delete', 'required' => false],
                ['name' => 'customers.import', 'required' => false],
                ['name' => 'customers.export', 'required' => false],
            ],
        ],
        [
            'key' => 'vehicles.manage',
            'label' => 'Gestión de vehículos',
            'description' => 'Permite consultar y actualizar vehículos con lectura requerida de clientes para asociación obligatoria.',
            'order' => 50,
            'permissions' => [
                ['name' => 'vehicles.view', 'required' => true],
                ['name' => 'customers.view', 'required' => true],
                ['name' => 'vehicles.create', 'required' => false],
                ['name' => 'vehicles.update', 'required' => false],
            ],
        ],
        [
            'key' => 'quotes.manage',
            'label' => 'Gestión de cotizaciones',
            'description' => 'Controla el ciclo completo de cotizaciones e ítems, con permisos de lectura requeridos de sus dependencias.',
            'order' => 60,
            'permissions' => [
                ['name' => 'quotes.view', 'required' => true],
                ['name' => 'customers.view', 'required' => true],
                ['name' => 'vehicles.view', 'required' => true],
                ['name' => 'products.view', 'required' => true],
                ['name' => 'services.view', 'required' => true],
                ['name' => 'bundles.view', 'required' => true],
                ['name' => 'quotes.create', 'required' => false],
                ['name' => 'quotes.update', 'required' => false],
                ['name' => 'quotes.delete', 'required' => false],
                ['name' => 'quotes.confirm', 'required' => false],
                ['name' => 'quotes.cancel', 'required' => false],
                ['name' => 'quotes.export', 'required' => false],
                ['name' => 'quotes.items.add', 'required' => false],
                ['name' => 'quotes.items.remove', 'required' => false],
            ],
        ],
        [
            'key' => 'products.manage',
            'label' => 'Gestión de productos',
            'description' => 'Administra catálogo e intercambio de productos.',
            'order' => 70,
            'permissions' => [
                ['name' => 'products.view', 'required' => true],
                ['name' => 'products.create', 'required' => false],
                ['name' => 'products.update', 'required' => false],
                ['name' => 'products.import', 'required' => false],
                ['name' => 'products.export', 'required' => false],
            ],
        ],
        [
            'key' => 'services.manage',
            'label' => 'Gestión de servicios',
            'description' => 'Administra catálogo e intercambio de servicios.',
            'order' => 80,
            'permissions' => [
                ['name' => 'services.view', 'required' => true],
                ['name' => 'services.create', 'required' => false],
                ['name' => 'services.update', 'required' => false],
                ['name' => 'services.import', 'required' => false],
                ['name' => 'services.export', 'required' => false],
            ],
        ],
        [
            'key' => 'bundles.manage',
            'label' => 'Gestión de paquetes',
            'description' => 'Administra paquetes y su disponibilidad para cotizar con lectura requerida de catálogos asociados.',
            'order' => 90,
            'permissions' => [
                ['name' => 'bundles.view', 'required' => true],
                ['name' => 'products.view', 'required' => true],
                ['name' => 'services.view', 'required' => true],
                ['name' => 'bundles.create', 'required' => false],
                ['name' => 'bundles.update', 'required' => false],
            ],
        ],
        [
            'key' => 'technicians.manage',
            'label' => 'Gestión de técnicos',
            'description' => 'Controla perfiles técnicos, disponibilidad y bloqueos con lectura requerida de horario operativo.',
            'order' => 100,
            'permissions' => [
                ['name' => 'technicians.view', 'required' => true],
                ['name' => 'schedule.view', 'required' => true],
                ['name' => 'technicians.create', 'required' => false],
                ['name' => 'technicians.update', 'required' => false],
                ['name' => 'technicians.availability.manage', 'required' => false],
                ['name' => 'technicians.blocks.manage', 'required' => false],
            ],
        ],
        [
            'key' => 'users.manage_basic',
            'label' => 'Gestión de usuarios',
            'description' => 'Gestiona consulta, creación, edición y estado de usuarios con lectura requerida de perfiles y skills.',
            'order' => 110,
            'permissions' => [
                ['name' => 'users.view', 'required' => true],
                ['name' => 'profiles.view', 'required' => true],
                ['name' => 'skills.view', 'required' => true],
                ['name' => 'users.create', 'required' => false],
                ['name' => 'users.update', 'required' => false],
                ['name' => 'users.manage_status', 'required' => false],
                ['name' => 'skills.assign', 'required' => false],
            ],
        ],
        [
            'key' => 'profiles.manage',
            'label' => 'Gestión de perfiles',
            'description' => 'Administra perfiles y matriz de permisos.',
            'order' => 120,
            'permissions' => [
                ['name' => 'profiles.view', 'required' => true],
                ['name' => 'profiles.create', 'required' => false],
                ['name' => 'profiles.update', 'required' => false],
                ['name' => 'profiles.assign_permissions', 'required' => false],
            ],
        ],
        [
            'key' => 'permissions.read',
            'label' => 'Consulta de permisos',
            'description' => 'Permite ver catálogo de permisos.',
            'order' => 130,
            'permissions' => [
                ['name' => 'permissions.view', 'required' => true],
            ],
        ],
        [
            'key' => 'skills.manage',
            'label' => 'Gestión de skills',
            'description' => 'Gestiona visibilidad y asignación de skills.',
            'order' => 140,
            'permissions' => [
                ['name' => 'skills.view', 'required' => true],
                ['name' => 'skills.assign', 'required' => false],
            ],
        ],
    ],
];
